schema_version: 1

context:
  name: cwltest
  version: "2.7.20260814150058"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 8aeeccfcc22be3b5ada5611c63e721c7f3251477959bcdc1e006e2fdbd27b967

build:
  number: 2
  skip: win
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - cwltest=cwltest.main:main

requirements:
  host:
    - pip
    - python
    - setuptools >=45
    - setuptools_scm >=8.0.4,<9
  run:
    - python
    - schema-salad >=5.0.20200220195218,<9
    - junit-xml >=1.8
    - pytest
    - defusedxml

tests:
  - python:
      imports:
        - cwltest
        - cwltest.tests
      pip_check: false
  - files:
      source:
        - tests/test-data
    requirements:
      run:
        - cwltool
        - pytest
    script:
      - cwltest --help
      - mkdir -p bin
      - ln -s $(command -v cwltool) bin/cwl-runner
      - chmod a+x bin/cwl-runner
      - PATH=$PATH:$PWD/bin CWLTOOL_OPTIONS=--no-container python -m pytest --pyargs cwltest -p pytester -o pytester_example_dir=tests/test-data -k 'not test_plugin'

about:
  license: Apache-2.0
  license_file: LICENSE
  summary: Common workflow language testing framework
  description: |
    This is a testing tool for checking the output of Tools and Workflows described
    with the Common Workflow Language.  Among other uses, it is used to run the CWL
    conformance tests.


  homepage: https://github.com/common-workflow-language/cwltest
  repository: https://github.com/common-workflow-language/cwltest
  documentation: http://cwltest.readthedocs.org/

extra:
  recipe-maintainers:
    - mr-c
